export const DONATION_KIND = {
  FOOD: 'FOOD', // pack size 25
  SOUP: 'SOUP', // pack size 18
}

export const DONATION_STATUS = {
  DRAFT: 'DRAFT',
  SCHEDULED_PICKUP: 'SCHEDULED_PICKUP',
  PICKED_UP: 'PICKED_UP',
  RECEIVED_WAREHOUSE: 'RECEIVED_WAREHOUSE',
  CANCELLED: 'CANCELLED',
}


export const ORDER_STATUS = {
  PENDING: 'PENDING',
  PREPARING: 'PREPARING',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
}
